### PR TITLE
fix: rename conflicting template project name

### PR DESCRIPTION
**Pull request by isaacbatst**
Just renames the project name in the basic template package.json

### CODE REVIEW

**Comment by davidcostadev** [comment]
@isaacbatst Thanks so much for your initiative, Could you change the example name as well, for something like `basic_example`, maybe?

**Comment by davidcostadev** [comment]
> @isaacbatst Thanks so much for your initiative, Could you change the example name as well, for something like `basic_example`, maybe?

Could you fix this conflict name too? 
https://travis-ci.org/davidcostadev/fastexpress/builds/600365244#L334

**Comment by isaacbatst** [comment]
@davidcostadev  For sure, I'll rename the examples and look at this other issue

**Comment by isaacbatst** [comment]
Just closed trying to rename the branch, but it didn't go as planned T-T

**Comment by davidcostadev** [comment]
No problem @isaacbatst, That is learning process

**Comment by isaacbatst** [comment]
Renamed all the examples names using as pattern the auth example name

**Comment by davidcostadev** [comment]
Oh, great, Thanks for your help!

**Pull request merged**
